#!/usr/bin/env bats

@test "inject just the functions" {
   run ../bin/lzt --dir data/zdf inject data/inject.1.in.lua
   [ "$status" -eq 0 ]
   [ "${lines[ 0]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[ 1]}" = "--LuaZDF-begin --with func1a func1b" ]
   [ "${lines[ 2]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[ 3]}" = "--ZFUNC-func1a-v1" ]
   [ "${lines[ 4]}" = "local function func1a()" ]
   [ "${lines[ 5]}" = '   return "a"' ]
   [ "${lines[ 6]}" = "end" ]
   [ "${lines[ 7]}" = "--ZFUNC-func1b-v1" ]
   [ "${lines[ 8]}" = "local function func1b()" ]
   [ "${lines[ 9]}" = '   return "b"' ]
   [ "${lines[10]}" = "end" ]
   [ "${lines[11]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[12]}" = "--LuaZDF-end" ]
   [ "${lines[13]}" = "--------------------------------------------------------------------------------" ]
}

@test "inject function with subfunctions" {
   run ../bin/lzt --dir data/zdf inject  data/inject.2.in.lua
   [ "$status" -eq 0 ]
   [ "${lines[ 0]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[ 1]}" = "--LuaZDF-begin --with func1a func2ax" ]
   [ "${lines[ 2]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[ 3]}" = "--ZFUNC-func1a-v1" ]
   [ "${lines[ 4]}" = "local function func1a()" ]
   [ "${lines[ 5]}" = '   return "a"' ]
   [ "${lines[ 6]}" = "end" ]
   [ "${lines[ 7]}" = "--ZFUNC-func2ax-v1" ]
   [ "${lines[ 8]}" = "local function func2ax()" ]
   [ "${lines[ 9]}" = '   return func1a().."x"' ]
   [ "${lines[10]}" = "end" ]
   [ "${lines[11]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[12]}" = "--LuaZDF-end" ]
   [ "${lines[13]}" = "--------------------------------------------------------------------------------" ]
}

@test "order injected functions right" {
   run ../bin/lzt --dir data/zdf inject data/inject.3.in.lua
   [ "$status" -eq 0 ]
   [ "${lines[ 0]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[ 1]}" = "--LuaZDF-begin --with func1a func1b func1dax func2ax" ]
   [ "${lines[ 2]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[ 3]}" = "--ZFUNC-func1a-v1" ]
   [ "${lines[ 4]}" = "local function func1a()" ]
   [ "${lines[ 5]}" = '   return "a"' ]
   [ "${lines[ 6]}" = "end" ]
   [ "${lines[ 7]}" = "--ZFUNC-func2ax-v1" ]
   [ "${lines[ 8]}" = "local function func2ax()" ]
   [ "${lines[ 9]}" = '   return func1a().."x"' ]
   [ "${lines[10]}" = "end" ]
   [ "${lines[11]}" = "--ZFUNC-func1b-v1" ]
   [ "${lines[12]}" = "local function func1b()" ]
   [ "${lines[13]}" = '   return "b"' ]
   [ "${lines[14]}" = "end" ]
   [ "${lines[15]}" = "--ZFUNC-func1dax-v1" ]
   [ "${lines[16]}" = "local function func1dax()" ]
   [ "${lines[17]}" = '   return "d"..func2ax()' ]
   [ "${lines[18]}" = "end" ]
   [ "${lines[19]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[20]}" = "--LuaZDF-end" ]
   [ "${lines[21]}" = "--------------------------------------------------------------------------------" ]
}

@test "appear selection works also for injection" {
   run ../bin/lzt --dir data/zdf inject data/inject.4.in.lua
   [ "$status" -eq 0 ]
   [ "${lines[ 0]}" = '--------------------------------------------------------------------------------' ]
   [ "${lines[ 1]}" = '--LuaZDF-begin --appear func1b func2y' ]
   [ "${lines[ 2]}" = '--------------------------------------------------------------------------------' ]
   [ "${lines[ 3]}" = 'local liby = require( "liby" ) --ZREQ-liby' ]
   [ "${lines[ 4]}" = '--ZFUNC-func1b-v1' ]
   [ "${lines[ 5]}" = 'local function func1b()' ]
   [ "${lines[ 6]}" = '   return "b"' ]
   [ "${lines[ 7]}" = 'end' ]
   [ "${lines[ 8]}" = '--ZFUNC-func2baxz-v1' ]
   [ "${lines[ 9]}" = 'local function func2baxz()' ]
   [ "${lines[10]}" = '   --ZFUNC-func2ax-v1' ]
   [ "${lines[11]}" = '   local function func2ax()' ]
   [ "${lines[12]}" = '      --ZFUNC-func1a-v1' ]
   [ "${lines[13]}" = '      local function func1a()' ]
   [ "${lines[14]}" = '         return "a"' ]
   [ "${lines[15]}" = '      end' ]
   [ "${lines[16]}" = '      return func1a().."x"' ]
   [ "${lines[17]}" = '   end' ]
   [ "${lines[18]}" = '   return func1b()..func2ax().."z"' ]
   [ "${lines[19]}" = 'end' ]
   [ "${lines[20]}" = '--ZFUNC-func2y-v2' ]
   [ "${lines[21]}" = 'local function func2y( ... )' ]
   [ "${lines[22]}" = '   --TODO' ]
   [ "${lines[23]}" = 'end' ]
   [ "${lines[24]}" = '--------------------------------------------------------------------------------' ]
   [ "${lines[25]}" = '--LuaZDF-end' ]
   [ "${lines[26]}" = '--------------------------------------------------------------------------------' ]
}

@test "possible to inject on more than one point in the code" {
   run ../bin/lzt --dir data/zdf inject data/inject.5.in.lua
   [ "$status" -eq 0 ]
   [ "${lines[ 0]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[ 1]}" = "--LuaZDF-begin --with func1a" ]
   [ "${lines[ 2]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[ 3]}" = "--ZFUNC-func1a-v1" ]
   [ "${lines[ 4]}" = "local function func1a()" ]
   [ "${lines[ 5]}" = '   return "a"' ]
   [ "${lines[ 6]}" = "end" ]
   [ "${lines[ 7]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[ 8]}" = "--LuaZDF-end" ]
   [ "${lines[ 9]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[10]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[11]}" = "--LuaZDF-begin --with func1a func1b" ]
   [ "${lines[12]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[13]}" = "--ZFUNC-func1a-v1" ]
   [ "${lines[14]}" = "local function func1a()" ]
   [ "${lines[15]}" = '   return "a"' ]
   [ "${lines[16]}" = "end" ]
   [ "${lines[17]}" = "--ZFUNC-func1b-v1" ]
   [ "${lines[18]}" = "local function func1b()" ]
   [ "${lines[19]}" = '   return "b"' ]
   [ "${lines[20]}" = "end" ]
   [ "${lines[21]}" = "--------------------------------------------------------------------------------" ]
   [ "${lines[22]}" = "--LuaZDF-end" ]
   [ "${lines[23]}" = "--------------------------------------------------------------------------------" ]
}
