#!/usr/bin/env bats

@test "makelib" {
   run ../bin/lzt --dir data/zdf makelib
   [ "$status" -eq 0 ]
   [ "${lines[ 0]}" = '-------------------------------------------------------------------------require' ]
   [ "${lines[ 1]}" = 'local ccc = require( "ccc" ) --ZREQ-ccc' ]
   [ "${lines[ 2]}" = 'local lfs = require( "lfs" ) --ZREQ-lfs' ]
   [ "${lines[ 3]}" = 'local liby = require( "liby" ) --ZREQ-liby' ]
   [ "${lines[ 4]}" = '-----------------------------------------------------------------------functions' ]
   [ "${lines[ 5]}" = '--ZFUNC-func1a-v1' ]
   [ "${lines[ 6]}" = 'local function func1a()' ]
   [ "${lines[ 7]}" = '   return "a"' ]
   [ "${lines[ 8]}" = 'end' ]
   [ "${lines[ 9]}" = '--ZFUNC-func1b-v1' ]
   [ "${lines[10]}" = 'local function func1b()' ]
   [ "${lines[11]}" = '   return "b"' ]
   [ "${lines[12]}" = 'end' ]
   [ "${lines[13]}" = '--ZFUNC-func2ax-v1' ]
   [ "${lines[14]}" = 'local function func2ax()' ]
   [ "${lines[15]}" = '   return func1a().."x"' ]
   [ "${lines[16]}" = 'end' ]
   [ "${lines[17]}" = '--ZFUNC-func1c-v1' ]
   [ "${lines[18]}" = 'local function func1c( ... )' ]
   [ "${lines[19]}" = '   --TODO' ]
   [ "${lines[20]}" = 'end' ]
   [ "${lines[21]}" = '--ZFUNC-func1dax-v1' ]
   [ "${lines[22]}" = 'local function func1dax()' ]
   [ "${lines[23]}" = '   return "d"..func2ax()' ]
   [ "${lines[24]}" = 'end' ]
   [ "${lines[25]}" = '--ZFUNC-func2baxz-v1' ]
   [ "${lines[26]}" = 'local function func2baxz()' ]
   [ "${lines[27]}" = '   return func1b()..func2ax().."z"' ]
   [ "${lines[28]}" = 'end' ]
   [ "${lines[29]}" = '--ZFUNC-func2y-v2' ]
   [ "${lines[30]}" = 'local function func2y( ... )' ]
   [ "${lines[31]}" = '   --TODO' ]
   [ "${lines[32]}" = 'end' ]
   [ "${lines[33]}" = '--ZFUNC-func3af-v1' ]
   [ "${lines[34]}" = 'local function func3af()' ]
   [ "${lines[35]}" = '   return func1a().."f"' ]
   [ "${lines[36]}" = 'end' ]
   [ "${lines[37]}" = 'local func3ag = (function() ' ]
   [ "${lines[38]}" = 'local g = "g"' ]
   [ "${lines[39]}" = '--ZFUNC-func3ag-v1' ]
   [ "${lines[40]}" = 'local function func3ag()' ]
   [ "${lines[41]}" = '   return func1a()..g' ]
   [ "${lines[42]}" = 'end' ]
   [ "${lines[43]}" = 'return func3ag' ]
   [ "${lines[44]}" = 'end)()' ]
   [ "${lines[45]}" = '--ZFUNC-xyz-v1' ]
   [ "${lines[46]}" = 'local function xyz( ... )' ]
   [ "${lines[47]}" = '   --TODO' ]
   [ "${lines[48]}" = 'end' ]
   [ "${lines[49]}" = '--------------------------------------------------------------------------module' ]
   [ "${lines[50]}" = 'local Z = {}' ]
   [ "${lines[51]}" = 'Z.func1a = func1a' ]
   [ "${lines[52]}" = 'Z.func1b = func1b' ]
   [ "${lines[53]}" = 'Z.func1c = func1c' ]
   [ "${lines[54]}" = 'Z.func1dax = func1dax' ]
   [ "${lines[55]}" = 'Z.func2ax = func2ax' ]
   [ "${lines[56]}" = 'Z.func2baxz = func2baxz' ]
   [ "${lines[57]}" = 'Z.func2y = func2y' ]
   [ "${lines[58]}" = 'Z.func3af = func3af' ]
   [ "${lines[59]}" = 'Z.func3ag = func3ag' ]
   [ "${lines[60]}" = 'Z.xyz = xyz' ]
   [ "${lines[61]}" = 'return Z' ]
}

@test "makelibe --with" {
   run ../bin/lzt --dir data/zdf makelib --with func2baxz
   [ "$status" -eq 0 ]
   [ "${lines[ 0]}" = '-----------------------------------------------------------------------functions' ]
   [ "${lines[ 1]}" = '--ZFUNC-func2baxz-v1' ]
   [ "${lines[ 2]}" = 'local function func2baxz()' ]
   [ "${lines[ 3]}" = '   --ZFUNC-func1b-v1' ]
   [ "${lines[ 4]}" = '   local function func1b()' ]
   [ "${lines[ 5]}" = '      return "b"' ]
   [ "${lines[ 6]}" = '   end' ]
   [ "${lines[ 7]}" = '   --ZFUNC-func2ax-v1' ]
   [ "${lines[ 8]}" = '   local function func2ax()' ]
   [ "${lines[ 9]}" = '      --ZFUNC-func1a-v1' ]
   [ "${lines[10]}" = '      local function func1a()' ]
   [ "${lines[11]}" = '         return "a"' ]
   [ "${lines[12]}" = '      end' ]
   [ "${lines[13]}" = '      return func1a().."x"' ]
   [ "${lines[14]}" = '   end' ]
   [ "${lines[15]}" = '   return func1b()..func2ax().."z"' ]
   [ "${lines[16]}" = 'end' ]
   [ "${lines[17]}" = '--------------------------------------------------------------------------module' ]
   [ "${lines[18]}" = 'local Z = {}' ]
   [ "${lines[19]}" = 'Z.func2baxz = func2baxz' ]
   [ "${lines[20]}" = 'return Z' ]
}
